timeout: 10
triggers:
  - name: merge-request
    type: github_pr
    runs:
      - name: flake8
        container: python:3.5-alpine
        host-tag: amd64
        script: flake8

  - name: build-container
    type: git_poller
    params:
      GIT_URL: "https://github.com/doanac/gavel-ci.git"
      GIT_POLL_REFS: "refs/heads/master"
    runs:
      - name: build-container
        container: docker:dind
        privileged: true
        host-tag: amd64
        script: build-container

scripts:
  flake8: |
    #!/bin/sh -ex
    pip3 install flake8
    flake8 --ignore=E722 --exclude=migrations/ ./

  build-container: |
    #!/bin/sh -e
    TAG=${GIT_SHA:0:6}

    unset DOCKER_HOST
    DOCKER_TLS_CERTDIR= /usr/local/bin/dockerd-entrypoint.sh --raw-logs >/archive/dockerd.log 2>&1 &
    /usr/local/bin/dockerd-entrypoint.sh --raw-logs >$archive/dockerd.log 2>&1 &
    for i in `seq 10` ; do
        sleep 1
        docker info >/dev/null 2>&1 && break
        if [ $i = 10 ] ; then
            echo 'Timed out trying to connect to internal docker host.' >&2
            exit 1
        fi
    done

    set -x
    docker build -t doanac/gavel-ci:$TAG --force-rm .
    docker tag doanac/gavel-ci:$TAG doanac/gavel-ci:latest

    if [ -f /secrets/dockerpass ] ; then
        set +x
        token=$(cat /secrets/dockerpass)
        mkdir -p $HOME/.docker
        docker login --username=doanac --password=$token
        set -x
        docker push doanac/gavel-ci:$TAG
        docker push doanac/gavel-ci:latest
    else
        echo "dockerpass not provided, skipping publishing step"
    fi
